//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyTicket.Domain.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> AirplaneId { get; set; }
        public Nullable<int> ScheludeId { get; set; }
        public Nullable<int> FlyTypeId { get; set; }
    
        public virtual Airplane Airplane { get; set; }
        public virtual City City { get; set; }
        public virtual FlyType FlyType { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
